###
POST {{content_host}}/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "java",
  "publishStatus": ""
}

###
GET {{content_host}}/content/course/40
Content-Type: application/json

###
GET {{content_host}}/content/courseTeacher/list/74
Content-Type: application/json